minimum_pre_commit_version: "4.0.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: mixed-line-ending
        args: ["--fix=lf"]

  - repo: local
    hooks:
      - id: make-l
        name: make l
        entry: make l
        language: system
        pass_filenames: false
      - id: make-t
        name: make t
        entry: make t
        language: system
        pass_filenames: false
