FROM rust:1.90-bookworm AS builder
WORKDIR /app
ENV CARGO_BUILD_JOBS=1 \
    CARGO_INCREMENTAL=0
COPY . .
RUN cargo build --release --bin uprava-server --bin uprava-node

FROM debian:bookworm-slim
COPY --from=builder /app/target/release/uprava-node /usr/local/bin/uprava-node
CMD ["uprava-node"]
