// @generated by scripts/protocol_check.py --write
// Rust uprava-protocol enums are the source of truth for these wire literals.

export const DEPLOYMENT_PROFILE_VALUES = ["controlled_dev"] as const;

export const NODE_PRESENCE_VALUES = [
  "reachable",
  "stale",
  "offline",
  "revoked",
] as const;

export const RUNTIME_SESSION_STATE_VALUES = [
  "starting",
  "ready",
  "running",
  "blocked",
  "stopping",
  "stopped",
  "interrupted",
  "resuming",
  "stale",
  "error",
  "expired",
] as const;

export const SESSION_THREAD_STATE_VALUES = [
  "created",
  "active",
  "detached",
  "stopped",
  "degraded",
] as const;

export const PLACEMENT_STATE_VALUES = [
  "pending",
  "validated",
  "missing",
  "read_only",
  "error",
] as const;

export const WARNING_SEVERITY_VALUES = [
  "info",
  "warning",
  "hard_block",
] as const;

export const CLIENT_LOG_LEVEL_VALUES = [
  "debug",
  "info",
  "warn",
  "error",
] as const;

export const COMMAND_STATE_VALUES = [
  "recorded",
  "pending_dispatch",
  "dispatched",
  "acknowledged",
  "completed",
  "failed",
  "blocked",
  "expired",
] as const;

export const COMMAND_KIND_VALUES = [
  "StartRuntime",
  "ResumeRuntime",
  "SendTurn",
  "ResolveApproval",
  "InterruptRuntime",
  "StopRuntime",
  "ValidateWorkspace",
  "RefreshResourceSnapshot",
  "ListWorkspaceTree",
  "ReadWorkspaceFile",
  "WriteWorkspaceFile",
  "RunWorkspaceCommand",
  "ReadWorkspaceDiff",
  "OpenWorkspaceTerminal",
  "AttachWorkspaceTerminal",
  "ResizeWorkspaceTerminal",
  "WriteWorkspaceTerminal",
  "CloseWorkspaceTerminal",
] as const;

export const MESSAGE_ROLE_VALUES = [
  "user",
  "assistant",
  "system",
  "runtime",
  "approval",
] as const;

export const WORKSPACE_ENTRY_KIND_VALUES = [
  "directory",
  "file",
  "symlink",
  "other",
] as const;

export const WORKSPACE_ENTRY_STATUS_VALUES = [
  "readable",
  "directory",
  "large",
  "binary",
  "ignored",
  "generated",
  "permission_denied",
  "outside_workspace",
  "missing",
  "not_file",
  "not_directory",
  "symlink",
  "error",
] as const;

export const WORKSPACE_COMMAND_INTENT_VALUES = ["command", "check"] as const;

export const WORKSPACE_TERMINAL_STATE_VALUES = [
  "opening",
  "running",
  "detached",
  "exited",
  "closed",
  "error",
] as const;

export const WORKSPACE_TERMINAL_CLIENT_FRAME_KIND_VALUES = [
  "input",
  "resize",
  "close",
  "ping",
] as const;

export const WORKSPACE_TERMINAL_STREAM_FRAME_KIND_VALUES = [
  "output",
  "status",
  "pong",
  "error",
] as const;
