#!/usr/bin/env bash
set -euo pipefail

release_manifest="${RELEASE_MANIFEST:?RELEASE_MANIFEST is required}"
release_id="${RELEASE_ID:?RELEASE_ID is required}"
git_sha="${GIT_SHA:?GIT_SHA is required}"
build_timestamp="${BUILD_TIMESTAMP:-$(date -u "+%Y-%m-%dT%H:%M:%SZ")}"
allow_unresolved="${ALLOW_UNRESOLVED_DIGESTS:-0}"
node_artifact_path="${NODE_ARTIFACT_PATH:?NODE_ARTIFACT_PATH is required}"
node_version="${UPRAVA_NODE_VERSION:-}"

image_repository() {
  local image="$1"
  local prefix
  local name

  if [[ "$image" == *@sha256:* ]]; then
    printf "%s\n" "${image%@sha256:*}"
    return
  fi

  prefix="${image%/*}"
  name="${image##*/}"
  if [[ "$name" == *:* ]]; then
    printf "%s/%s\n" "$prefix" "${name%%:*}"
    return
  fi

  printf "%s\n" "$image"
}

resolve_image() {
  local image="$1"
  local digest
  local repository

  if [[ "$image" == *@sha256:* ]]; then
    printf "%s\n" "$image"
    return
  fi

  digest="$(
    docker buildx imagetools inspect \
      --format '{{json .Manifest.Digest}}' \
      "$image" 2>/dev/null | tr -d '"'
  )" || digest=""

  if [[ -n "$digest" && "$digest" != "null" ]]; then
    repository="$(image_repository "$image")"
    printf "%s@%s\n" "$repository" "$digest"
    return
  fi

  if [[ "$allow_unresolved" == "1" ]]; then
    printf "%s\n" "$image"
    return
  fi

  printf "Could not resolve digest for %s\n" "$image" >&2
  printf "Set ALLOW_UNRESOLVED_DIGESTS=1 only for local dry runs.\n" >&2
  exit 1
}

require_image_var() {
  local name="$1"
  local value="${!name:-}"

  if [[ -z "$value" ]]; then
    printf "%s is required\n" "$name" >&2
    exit 1
  fi

  resolve_image "$value"
}

core_image="$(require_image_var UPRAVA_CORE_IMAGE)"
web_image="$(require_image_var UPRAVA_WEB_IMAGE)"
node_image="$(require_image_var UPRAVA_NODE_IMAGE)"
node_sha="$(scripts/extract-node-artifact.sh "$node_image" "$node_artifact_path")"

mkdir -p "$(dirname "$release_manifest")"
tmp_file="$(mktemp)"

{
  printf "# Generated by make release-manifest. Do not edit on the server.\n"
  printf "UPRAVA_RELEASE_ID=%s\n" "$release_id"
  printf "UPRAVA_RELEASE_SHA=%s\n" "$git_sha"
  printf "UPRAVA_RELEASE_AT=%s\n" "$build_timestamp"
  printf "UPRAVA_CORE_IMAGE=%s\n" "$core_image"
  printf "UPRAVA_WEB_IMAGE=%s\n" "$web_image"
  printf "UPRAVA_NODE_ARTIFACT=%s\n" "$node_image"
  printf "UPRAVA_NODE_SHA256=%s\n" "$node_sha"
  if [[ -n "$node_version" ]]; then
    printf "UPRAVA_NODE_VERSION=%s\n" "$node_version"
  fi
} >"$tmp_file"

mv "$tmp_file" "$release_manifest"
printf "Wrote %s\n" "$release_manifest"
